name: Run Backend Tests on Pull Request

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  MONGO_URI: mongodb://localhost:27017/testdb
  NODE_ENV: test
    

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run backend tests
      working-directory: ./backend
      run: npm test
